name: zeroq
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter


  rename: ^3.0.0
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  dio: ^5.3.3
  shimmer: ^3.0.0
  permission_handler: ^11.4.0
  flutter_svg: ^2.0.7
  get_storage: ^2.1.1
  encrypted_shared_preferences: ^3.0.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  razorpay_flutter: ^1.3.7
  google_geocoding_api: ^1.5.2
  quickalert: ^1.1.0
  shimmer_pro: ^0.0.6
  url_launcher: ^6.2.6
  device_preview: ^1.2.0
  google_maps_flutter: ^2.10.0
  provider: ^6.1.2
  intl: ^0.19.0
  graphql_flutter: ^5.2.0-beta.8
  http: ^1.3.0
  confetti: ^0.8.0
  image_picker: ^1.1.2
  toggle_switch: ^2.3.0
  cached_network_image: ^3.4.1
  path: ^1.9.1
  http_parser: ^4.1.2
  decimal: ^3.0.0
  google_places_flutter: ^2.0.1
  shared_preferences: ^2.5.2
  syncfusion_flutter_datepicker: ^29.1.33



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

  web:
    generate: true
    image_path: "assets/icons/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/onboarding1.png
    - assets/onboarding2.png
    - assets/onboarding3.png
    - assets/icons/
    - assets/icons/locationicon.png
    - assets/icons/delivery1.png
    - assets/images/
    - assets/images/food/
    - assets/images/dining/
    - assets/icons/delivery1.png
    - assets/images/menu.svg